### ISSUE TITLE
i make code

### ISSUE THREAD

**Issue by notpoiu** [applesfruit/MCPMicrosoftLogin#1]
eeeeee

**Comment by notpoiu** [comment]
not open auth but the code

**Comment by applesfruit** [comment]
wat

**Comment by notpoiu** [comment]
i make the code in 401

**Comment by notpoiu** [comment]
yey

**Comment by applesfruit** [comment]
i found this somewhere it wasnt by u lol

**Comment by notpoiu** [comment]
where did you find it from then

**Comment by applesfruit** [comment]
eric server

**Comment by notpoiu** [comment]
meh but i made the code in 401 clarint and gave it to trashies 21 and its the exact same function name so its kinda weird lol
